title: "Building Websites in Github"
description: "This research project develops training materials for researchers wanting to learn to build project websites in github with Github pages."
email: "team@carpentries.org"
twitter: "https://twitter.com/thecarpentries"
team_members: [
    {name: "Tom Cat", role: "project lead", start_date: "2020-10-01"},
    {name: "Jane Smith", role: "maintainer", start_date: "2018-03-15"},
    {name: "Albert Hamilton", role: "editor", start_date: "2017-12-01"},
    {name: "Alice Dauncey", role: "developer", start_date: "2020-09-15"},
]
collections:
    - posts:
        output: true
